### ISSUE TITLE
rostful error

### ISSUE THREAD

**Issue by rvipin17** [asmodehn/rostful-examples#5]
Hi @asmodehn 

python -m rostful run --ros; 
running this command, shows the following error: 

```
WARNING:root:ZMQ : Protobuf message implementation not found. Using pickle based protocol
Usage: __main__.py run [OPTIONS]
Try "__main__.py run --help" for help.

Error: no such option: --ros  Did you mean --ros-arg?
```

**Comment by asmodehn** [comment]
Yes. So what are you trying to do ?

**Comment by rvipin17** [comment]
I was trying to install rostful using python way and got the above error, after solving all the dependencies I am able to run rostful. However, if I launch turtlebotsim I am not able to receive any topic message at http://localhost:8080/ros/turtle1/pose, it throws http response as: 

`404 : /turtle1/cmd_vel
WARNING:flask.app:404 : /turtle1/cmd_vel
INFO:werkzeug:127.0.0.1 - - [11/Oct/2018 17:40:23] "GET /ros/turtle1/cmd_vel HTTP/1.1" 404 -`
 
**Complete log after launching rostful:** 

`addverb@addverb-Vostro-15-3568:~/catkin_mir_ws$ roslaunch rostful rostful.launch... logging to /home/addverb/.ros/log/36cec206-cd4d-11e8-996d-dca26629e16b/roslaunch-addverb-Vostro-15-3568-18987.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://addverb-Vostro-15-3568:37511/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rostful/enable_cache: False
 * /rostful/params: []
 * /rostful/services: []
 * /rostful/topics: ['turtle1/pose']
 * /rosversion: 1.12.14

NODES
  /
    rostful (rostful/rostful)

ROS_MASTER_URI=http://localhost:11311

process[rostful-1]: started with pid [19005]
+ python -tt -m rostful run -h 127.0.0.1 -p 8080 -s flask -c /home/addverb/catkin_mir_ws/src/rostful/instance/rostful.cfg -l /home/addverb/catkin_mir_ws/src/rostful/instance/rostful.log '--ros-arg=~connections_list:=/connection_cache/list' '--ros-arg=~connections_diff:=/connection_cache/diff' --ros-arg=__name:=rostful --ros-arg=__log:=/home/addverb/.ros/log/36cec206-cd4d-11e8-996d-dca26629e16b/rostful-1.log
WARNING:root:ZMQ : Protobuf message implementation not found. Using pickle based protocol
INFO:flask.app:Loading config from /home/addverb/catkin_mir_ws/src/rostful/instance/rostful.cfg
INFO:flask.app:Registering api Blueprint on /ros
INFO:flask.app:Registering main Blueprint
DEBUG:flask.app:Rostful Rules : Map([<Rule '/frontend/' (HEAD, OPTIONS, GET) -> main.ros_list>,
 <Rule '/ros/' (HEAD, POST, OPTIONS, GET) -> api_0_1.backend>,
 <Rule '/' (HEAD, OPTIONS, GET) -> _redirect_._to_.ros_list>,
 <Rule '/frontend/<rosname>' (HEAD, OPTIONS, GET) -> main.ros_interface>,
 <Rule '/static/<filename>' (HEAD, OPTIONS, GET) -> static>,
 <Rule '/ros/<rosname>' (HEAD, POST, OPTIONS, GET) -> api_0_1.backend>])
INFO:flask.app:rostful started with : host 127.0.0.1 port 8080 config /home/addverb/catkin_mir_ws/src/rostful/instance/rostful.cfg logfile /home/addverb/catkin_mir_ws/src/rostful/instance/rostful.log ros_args (u'~connections_list:=/connection_cache/list', u'~connections_diff:=/connection_cache/diff', u'__name:=rostful', u'__log:=/home/addverb/.ros/log/36cec206-cd4d-11e8-996d-dca26629e16b/rostful-1.log')
WARNING:root:Setting up pyros <class 'pyros_interfaces_ros.pyros_ros.PyrosROS'> node...
WARNING:root:Setting up pyros actual client...
INFO:werkzeug: * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)`

**Environment :** 
Ubuntu 16.04 and ROS-Kinetic

**Steps to reproduce:** 
Navigate to your workspace,
$ cd ~/catkin_ws/src 
$ git clone -b gopher-devel --recursive https://github.com/pyros-dev/rostful.git
$ cd rostful
$ cd deps
$ git clone --recursive https://github.com/pyros-dev/pyros-utils.git
$ cd pyros-utils
$ pip install .
$ cd ..
$ git clone --recursive https://github.com/pyros-dev/pyros.git
$ cd pyros
$ pip install .
$ cd ../..
$ pip install .
$ pip install -r requirements.txt
$ cd ../..
$ catkin_make
$ source devel/setup.bash
$ roslaunch rostful rostful.launch

The above steps will solve all dependencies with rostful. Browse to localhost:8080, you’ll be able to see your rostful local host running. 
Then,
$ roscore
$ rosrun turtlesim turtlesim_node

Check all the topics: rostopic list
/rosout
/rosout_agg
/turtle1/cmd_vel
/turtle1/color_sensor
/turtle1/pose

But, I don't see any data received in my localhost.

**Comment by asmodehn** [comment]
Looking at your paremeters, only turtle1/pose will be exposed by rostful.
Rostful will then transfer this config to the pyros node running (there
might be bugs on there depending your version of the packages or the way
you run things, I was fixing some last time I checked it). Pyros had some
dynamic reconfigure to expose this kind of things (so you can check with a
rqt client), but i m not sure if it s still fully working or not...

So do not be afraid to step through and debug your python code. We have
debugging tools, use them (I know a lot of roboticist/embedded devs prefer
the simplicity of printf, but maximizing the way you use all the tools is
very important). Pycharm will work great if you manage to get ROS out of
the way (but that might require pyros-setup and a bit of python expertise).

Good luck on that long journey to find the right tool for each of the jobs
;-) My preference goes to doing everything in python and forgetting ROS as
much as I can. I just didnt have enough time to package ROS into a pip
package ;-)

**Comment by asmodehn** [comment]
Few things : 
- Be mindful of where you install your dependencies ( `pip install .` -> where does it go ? how does the interpreter can `import` that later ? how are we sure we get the proper version, and not another version in a different place ? ).
- Not sure what catkin_make is used for here ? Its all python code isn't it ? you don't need to compile anything I believe...
- `source devel/setup.bash` will change your environment, including where python can find your packages... you might not be running the version you think you are, especially if you have the same module installed by ROS packages and via python...
- ` roslaunch rostful rostful.launch` is a just a convoluted way to call an executable via command line, I usually prefer starting the program directly.
- in your parameters,I remember implementing simple regex support, so you might want to try things like `'.*'` to expose all services for example.
- I remember also being in the process of splitting 'topics' into 'publishers'/'subscribers' so you might want to try that as well.

**Comment by geg58** [comment]
@asmodehn It would be great if you update readme with correct example usage for python way. The error listed at the beginning of the thread still exists when you run: `python -m rostful run --ros`

**Comment by asmodehn** [comment]
I recently started testing the README steps again, as I need to do it to test melodic anyway.
Work in progress visible there : https://github.com/asmodehn/rostful-examples/pull/6

**Comment by asmodehn** [comment]
I recently got the documented workflow working with melodic.
It would be good if someone can check  #6 and report any problems.
